let applications = [];
let filter = 'all';
let showAll = false;
const rows = document.querySelector('#applicationRows');
const healthClass = value => value.toLowerCase().replace(/\s+/g, '-');
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const averageProgress = profiles => Math.round(profiles.reduce((total, profile) => total + profile.progress, 0) / profiles.length);
function visibleApplications() { return applications.filter(app => filter === 'all' || (filter === 'attention' ? app.health !== 'On track' : app.health === 'Blocked')); }
function applicationRow(app, index) {
  const progress = averageProgress(app.accessProfiles);
  const profiles = app.accessProfiles.map(profile => `<tr><td><strong>${escapeHtml(profile.name)}</strong></td><td>${profile.population.toLocaleString()}</td><td><div class="bar-cell"><span class="tiny-bar"><i style="width:${profile.progress}%"></i></span><small>${profile.progress}%</small></div></td><td><span class="profile-status ${healthClass(profile.status)}">${escapeHtml(profile.status)}</span></td><td>${escapeHtml(profile.owner)}</td></tr>`).join('');
  return `<tr class="application-row"><td><button class="expand-button" data-expand="${index}" aria-expanded="false" aria-controls="profiles-${index}">+</button><span class="app-name">${escapeHtml(app.name)}</span><span class="app-sub">${escapeHtml(app.type)} · ${app.accessProfiles.length} access profiles</span></td><td><span class="criticality ${healthClass(app.criticality)}">${escapeHtml(app.criticality)}</span></td><td class="phase">${escapeHtml(app.phase)}</td><td><div class="bar-cell"><span class="tiny-bar"><i style="width:${progress}%"></i></span><small>${progress}%</small></div></td><td>${escapeHtml(app.owner)}</td><td><span class="health ${healthClass(app.health)}">${escapeHtml(app.health)}</span></td><td><button class="row-action" aria-label="More options for ${escapeHtml(app.name)}">•••</button></td></tr><tr class="profile-detail" id="profiles-${index}" hidden><td colspan="7"><div class="profile-detail-inner"><p>Access profile migration status</p><table class="profile-table"><thead><tr><th>Access profile</th><th>Population</th><th>Progress</th><th>Status</th><th>Business owner</th></tr></thead><tbody>${profiles}</tbody></table></div></td></tr>`;
}
function updateSummary() { const attention = applications.filter(app => app.health !== 'On track').length; const blocked = applications.filter(app => app.health === 'Blocked').length; document.querySelector('#appCount').textContent = applications.length; document.querySelector('#onTrackCount').textContent = applications.length - attention; document.querySelector('#attentionCount').textContent = attention; document.querySelector('#filterAll').textContent = applications.length; document.querySelector('#filterAttention').textContent = attention; document.querySelector('#filterBlocked').textContent = blocked; }
function render() { const visible = visibleApplications(); const display = showAll ? visible : visible.slice(0, 5); rows.innerHTML = display.map(applicationRow).join(''); document.querySelector('#viewAllButton').innerHTML = `${showAll ? 'Show fewer applications' : `View all applications (${visible.length})`} <span>→</span>`; updateSummary(); }
function toast(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { filter = button.dataset.filter; showAll = false; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item === button)); render(); }));
document.querySelector('#viewAllButton').addEventListener('click', () => { showAll = !showAll; render(); });
rows.addEventListener('click', event => { const button = event.target.closest('[data-expand]'); if (!button) return; const detail = document.querySelector(`#profiles-${button.dataset.expand}`); const expanded = button.getAttribute('aria-expanded') === 'true'; button.setAttribute('aria-expanded', String(!expanded)); button.textContent = expanded ? '+' : '−'; detail.hidden = expanded; });
const dialog = document.querySelector('#applicationDialog'); document.querySelector('#addButton').addEventListener('click', () => dialog.showModal()); document.querySelector('#closeDialog').addEventListener('click', () => dialog.close());
const range = document.querySelector('[name=progress]'); range.addEventListener('input', () => { document.querySelector('#progressOutput').textContent = `${range.value}%`; });
document.querySelector('#applicationForm').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.target); applications.unshift({ name: data.get('name'), type: 'New application', criticality: 'Medium', phase: data.get('phase'), owner: data.get('owner'), health: data.get('health'), accessProfiles: [{ name: 'Profile to be defined', population: 0, progress: Number(data.get('progress')), status: data.get('phase'), owner: data.get('owner') }] }); event.target.reset(); document.querySelector('#progressOutput').textContent = '0%'; dialog.close(); filter = 'all'; document.querySelectorAll('.filter').forEach((item, index) => item.classList.toggle('active', index === 0)); render(); toast('Application added to the migration tracker.'); });
document.querySelector('#exportButton').addEventListener('click', () => { const data = [['Application', 'Criticality', 'Access profile', 'Population', 'Progress', 'Status', 'Owner'], ...applications.flatMap(app => app.accessProfiles.map(profile => [app.name, app.criticality, profile.name, profile.population, `${profile.progress}%`, profile.status, profile.owner]))]; const blob = new Blob([data.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'isc-access-profile-migration-report.csv' }); link.click(); URL.revokeObjectURL(link.href); toast('Access profile CSV report downloaded.'); });
document.querySelector('#decisionButton').addEventListener('click', () => { document.querySelector('.focus-panel').scrollIntoView({ behavior: 'smooth' }); toast('3 sponsor decisions are ready for review.'); });
fetch('data/migration-sample.json').then(response => { if (!response.ok) throw new Error('Could not load sample data'); return response.json(); }).then(data => { applications = data.applications; render(); }).catch(() => { rows.innerHTML = '<tr><td colspan="7" class="load-error">Unable to load the migration sample data. Please serve the dashboard through a web server.</td></tr>'; });
