let applications = [];
let filter = 'all';
let showAll = false;
const rows = document.querySelector('#applicationRows');
const healthClass = value => value.toLowerCase().replace(/\s+/g, '-');
const escapeHtml = value => String(value ?? '—').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const migratedProfiles = app => app.accessProfiles.filter(profile => profile.matchStatus === 'Migrated').length;
const applicationStatus = app => !app.entraApplication.exists ? 'Not migrated' : migratedProfiles(app) === app.accessProfiles.length ? 'Migrated' : 'Partial';
const applicationCoverage = app => Math.round((migratedProfiles(app) / app.accessProfiles.length) * 100);
function visibleApplications() { return applications.filter(app => filter === 'all' || applicationStatus(app).toLowerCase().replace(' ', '-') === filter); }
function applicationRow(app, index) {
  const status = applicationStatus(app); const coverage = applicationCoverage(app);
  const profiles = app.accessProfiles.map(profile => `<tr><td><strong>${escapeHtml(profile.adName)}</strong></td><td>${escapeHtml(profile.entraName)}</td><td>${profile.population.toLocaleString()}</td><td><span class="profile-status ${healthClass(profile.matchStatus)}">${escapeHtml(profile.matchStatus)}</span></td><td>${escapeHtml(profile.owner)}</td></tr>`).join('');
  const entraComparison = app.entraApplication.exists ? app.entraApplication.name : 'Entra application missing';
  return `<tr class="application-row"><td><button class="expand-button" data-expand="${index}" aria-expanded="false" aria-controls="profiles-${index}">+</button><span class="app-name">${escapeHtml(app.adApplication.name)}</span><span class="app-sub">${escapeHtml(app.name)} · ${app.accessProfiles.length} access profiles</span></td><td><span class="criticality ${healthClass(app.criticality)}">${escapeHtml(app.criticality)}</span></td><td class="phase">${escapeHtml(entraComparison)}</td><td><div class="bar-cell"><span class="tiny-bar"><i style="width:${coverage}%"></i></span><small>${coverage}%</small></div></td><td>${escapeHtml(app.owner)}</td><td><span class="health ${healthClass(status)}">${status}</span></td><td><button class="row-action" aria-label="More options for ${escapeHtml(app.name)}">•••</button></td></tr><tr class="profile-detail" id="profiles-${index}" hidden><td colspan="7"><div class="profile-detail-inner"><p>AD to Entra access profile comparison</p><table class="profile-table"><thead><tr><th>AD access profile</th><th>Entra access profile</th><th>Population</th><th>Comparison</th><th>Business owner</th></tr></thead><tbody>${profiles}</tbody></table></div></td></tr>`;
}
function updateSummary() { const migrated = applications.filter(app => applicationStatus(app) === 'Migrated').length; const partial = applications.filter(app => applicationStatus(app) === 'Partial').length; const notMigrated = applications.filter(app => applicationStatus(app) === 'Not migrated').length; const completion = applications.length ? Math.round((migrated / applications.length) * 100) : 0; document.querySelector('#appCount').textContent = applications.length; document.querySelector('#onTrackCount').textContent = migrated; document.querySelector('#attentionCount').textContent = partial + notMigrated; document.querySelector('#filterAll').textContent = applications.length; document.querySelector('#filterAttention').textContent = partial; document.querySelector('#filterBlocked').textContent = notMigrated; document.querySelector('#overallCompletion').textContent = completion; document.querySelector('#completionBar').style.width = `${completion}%`; document.querySelector('#completionNote').textContent = `${migrated} of ${applications.length} applications match in Entra`; }
function render() { const visible = visibleApplications(); const display = showAll ? visible : visible.slice(0, 5); rows.innerHTML = display.map(applicationRow).join(''); document.querySelector('#viewAllButton').innerHTML = `${showAll ? 'Show fewer applications' : `View all applications (${visible.length})`} <span>→</span>`; updateSummary(); }
function toast(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { filter = button.dataset.filter; showAll = false; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item === button)); render(); }));
document.querySelector('#viewAllButton').addEventListener('click', () => { showAll = !showAll; render(); });
rows.addEventListener('click', event => { const button = event.target.closest('[data-expand]'); if (!button) return; const detail = document.querySelector(`#profiles-${button.dataset.expand}`); const expanded = button.getAttribute('aria-expanded') === 'true'; button.setAttribute('aria-expanded', String(!expanded)); button.textContent = expanded ? '+' : '−'; detail.hidden = expanded; });
const dialog = document.querySelector('#applicationDialog'); document.querySelector('#addButton').addEventListener('click', () => dialog.showModal()); document.querySelector('#closeDialog').addEventListener('click', () => dialog.close());
const range = document.querySelector('[name=progress]'); range.addEventListener('input', () => { document.querySelector('#progressOutput').textContent = `${range.value}%`; });
document.querySelector('#applicationForm').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.target); const migrated = Number(data.get('progress')) === 100; applications.unshift({ name: data.get('name'), type: 'New application', criticality: 'Medium', owner: data.get('owner'), adApplication: { name: `AD - ${data.get('name')}`, exists: true }, entraApplication: { name: migrated ? `Entra - ${data.get('name')}` : null, exists: migrated }, accessProfiles: [{ adName: 'AD - Profile to be defined', entraName: migrated ? 'Entra - Profile to be defined' : null, population: 0, matchStatus: migrated ? 'Migrated' : 'Not migrated', owner: data.get('owner') }] }); event.target.reset(); document.querySelector('#progressOutput').textContent = '0%'; dialog.close(); filter = 'all'; document.querySelectorAll('.filter').forEach((item, index) => item.classList.toggle('active', index === 0)); render(); toast('Application added to the AD / Entra comparison.'); });
document.querySelector('#exportButton').addEventListener('click', () => { const data = [['Application', 'Criticality', 'AD access profile', 'Entra access profile', 'Population', 'Comparison status', 'Owner'], ...applications.flatMap(app => app.accessProfiles.map(profile => [app.name, app.criticality, profile.adName, profile.entraName ?? '', profile.population, profile.matchStatus, profile.owner]))]; const blob = new Blob([data.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'ad-entra-access-profile-comparison.csv' }); link.click(); URL.revokeObjectURL(link.href); toast('AD / Entra comparison CSV downloaded.'); });
document.querySelector('#decisionButton').addEventListener('click', () => { document.querySelector('.focus-panel').scrollIntoView({ behavior: 'smooth' }); toast('3 sponsor decisions are ready for review.'); });
fetch('data/migration-sample.json').then(response => { if (!response.ok) throw new Error('Could not load sample data'); return response.json(); }).then(data => { applications = data.applications; render(); }).catch(() => { rows.innerHTML = '<tr><td colspan="7" class="load-error">Unable to load the migration sample data. Please serve the dashboard through a web server.</td></tr>'; });
